stages:
  split:
    cmd: python src/split_into_batches.py
    deps:
      - src/split_into_batches.py
    outs:
      - data/incoming

  ingest:
    cmd: python src/ingest_bronze.py
    deps:
      - src/ingest_bronze.py
      - data/incoming
    outs:
      - data/bronze

  validate:
    cmd: python src/validate_silver.py
    deps:
      - src/validate_silver.py
      - data/bronze
    outs:
      - data/silver/silver_all.csv

  transform:
    cmd: python src/transform_silver.py
    deps:
      - src/transform_silver.py
      - data/silver/silver_all.csv
    outs:
      - data/silver/transformed_silver.csv

  build:
    cmd: python src/build_gold.py
    deps:
      - src/build_gold.py
      - data/silver/transformed_silver.csv
    outs:
      - data/gold
